//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AG_TSP.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AG_TSP.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ajuda.
        /// </summary>
        internal static string ajuda {
            get {
                return ResourceManager.GetString("ajuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Para mais informações entrar em contato com os desenvolvedores:
        /// guilherme-prado-@outlook.com.br
        /// caiojunt@gmail.com
        /// ibrunoguiraldelli@gmail.com
        ///
        ///---AG PRINCIPAL---
        ///
        ///1 - Inserir Pontos / Importar TSPLIB
        ///
        ///  Para a execução do AG é necessario inserir os pontos (cidades) na tela, isto pode ser feito clicando na tela ou fazendo download da TSPLIB (https://www.iwr.uni-heidelberg.de/groups/comopt/software/TSPLIB95/tsp/), pressionando o botão &quot;Importar&quot; este irá abrir uma nova janela onde você deve naveg [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string ajuda_dicas {
            get {
                return ResourceManager.GetString("ajuda_dicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Algoritmo Genético.
        /// </summary>
        internal static string algoritmo {
            get {
                return ResourceManager.GetString("algoritmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alterar.
        /// </summary>
        internal static string alterar {
            get {
                return ResourceManager.GetString("alterar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Criar População.
        /// </summary>
        internal static string btn_criar_pop {
            get {
                return ResourceManager.GetString("btn_criar_pop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Executar.
        /// </summary>
        internal static string btn_executar {
            get {
                return ResourceManager.GetString("btn_executar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inserir.
        /// </summary>
        internal static string btn_inserir {
            get {
                return ResourceManager.GetString("btn_inserir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Limpar.
        /// </summary>
        internal static string btn_limpar {
            get {
                return ResourceManager.GetString("btn_limpar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Como Usar.
        /// </summary>
        internal static string como_usar {
            get {
                return ResourceManager.GetString("como_usar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurações.
        /// </summary>
        internal static string configuracoes {
            get {
                return ResourceManager.GetString("configuracoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desabilitado.
        /// </summary>
        internal static string desabilitado {
            get {
                return ResourceManager.GetString("desabilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Elitismo:.
        /// </summary>
        internal static string elitismo {
            get {
                return ResourceManager.GetString("elitismo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Escolha um idioma.
        /// </summary>
        internal static string escolha_idioma {
            get {
                return ResourceManager.GetString("escolha_idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Evoluções:.
        /// </summary>
        internal static string evolucao {
            get {
                return ResourceManager.GetString("evolucao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a População Geral.
        /// </summary>
        internal static string geral_populacao {
            get {
                return ResourceManager.GetString("geral_populacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grafico.
        /// </summary>
        internal static string grafico {
            get {
                return ResourceManager.GetString("grafico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idioma.
        /// </summary>
        internal static string idioma {
            get {
                return ResourceManager.GetString("idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Importar.
        /// </summary>
        internal static string importar {
            get {
                return ResourceManager.GetString("importar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Individuo.
        /// </summary>
        internal static string individuo {
            get {
                return ResourceManager.GetString("individuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informações.
        /// </summary>
        internal static string informacao {
            get {
                return ResourceManager.GetString("informacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inglês.
        /// </summary>
        internal static string ingles {
            get {
                return ResourceManager.GetString("ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inserir Cidades:.
        /// </summary>
        internal static string inserir_cidades {
            get {
                return ResourceManager.GetString("inserir_cidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Media Aptidão .
        /// </summary>
        internal static string media_fitness {
            get {
                return ResourceManager.GetString("media_fitness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Media População.
        /// </summary>
        internal static string media_pop {
            get {
                return ResourceManager.GetString("media_pop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Melhor Individuo:.
        /// </summary>
        internal static string melhor_ind {
            get {
                return ResourceManager.GetString("melhor_ind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Menor Distância:.
        /// </summary>
        internal static string menor_dist {
            get {
                return ResourceManager.GetString("menor_dist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mutação.
        /// </summary>
        internal static string mutacao {
            get {
                return ResourceManager.GetString("mutacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Novo Indivíduo.
        /// </summary>
        internal static string novo_ind {
            get {
                return ResourceManager.GetString("novo_ind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a População.
        /// </summary>
        internal static string populacao {
            get {
                return ResourceManager.GetString("populacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Português.
        /// </summary>
        internal static string portugues {
            get {
                return ResourceManager.GetString("portugues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cidades:.
        /// </summary>
        internal static string qtnd_cidades {
            get {
                return ResourceManager.GetString("qtnd_cidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Elitismo de .
        /// </summary>
        internal static string qtnd_ind_elitismo {
            get {
                return ResourceManager.GetString("qtnd_ind_elitismo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Torneio com :.
        /// </summary>
        internal static string qtnd_ind_torneio {
            get {
                return ResourceManager.GetString("qtnd_ind_torneio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sair.
        /// </summary>
        internal static string sair {
            get {
                return ResourceManager.GetString("sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string salvar {
            get {
                return ResourceManager.GetString("salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tamanho Pop:.
        /// </summary>
        internal static string tamanho_pop {
            get {
                return ResourceManager.GetString("tamanho_pop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Taxa de Crossover:.
        /// </summary>
        internal static string taxa_cruzamento {
            get {
                return ResourceManager.GetString("taxa_cruzamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Taxa de Mutação:.
        /// </summary>
        internal static string taxa_mutacao {
            get {
                return ResourceManager.GetString("taxa_mutacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tela Principal.
        /// </summary>
        internal static string tela_principal {
            get {
                return ResourceManager.GetString("tela_principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo Cruzamento:.
        /// </summary>
        internal static string tipo_cruzamento {
            get {
                return ResourceManager.GetString("tipo_cruzamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo Mutação:.
        /// </summary>
        internal static string tipo_mutacao {
            get {
                return ResourceManager.GetString("tipo_mutacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo Seleção:.
        /// </summary>
        internal static string tipo_selecao {
            get {
                return ResourceManager.GetString("tipo_selecao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Torneio, .
        /// </summary>
        internal static string torneio {
            get {
                return ResourceManager.GetString("torneio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Torneio:.
        /// </summary>
        internal static string torneio_dois_pontos {
            get {
                return ResourceManager.GetString("torneio_dois_pontos", resourceCulture);
            }
        }
    }
}
